### ISSUE TITLE
gentílicos vs demonyms

### ISSUE THREAD

**Issue by livyreal** [own-pt/openWordnet-PT#101]
Este issue é para reportar a discordância entre Valeria e Livy na análise dos gentilicos e demonyms em PT e EN.

Para Valeria, em sentenças como:

Tenho três amigos estrangeiros. O americano fala muito.  (I have three friends. The american ONE talks a lot.)

"americano" é uma extensão metafórica do gentílico "americano"... ainda que não apareça na estrutura superficial "o amigo americano", é isto que a sentença representa. Assim, em "o americano fala muito", "americano" deve ser entendido como "adjetivo" usado metaforicamente.

Livy discorda e pensa que "americano" aí é o nome. 

Decidir como analisamos estas frases tem várias consequências:

- gentílicos e deomnyms funcionam da mesma forma em PT/EN?
- Se não, encontramos uma classe de palavras que sintaticamente funciona de maneira sempre diferente comparando EN/PT? Isto deve refletir nas relações entre PWN e OWN-PT?
- demonyms em PT poderiam significar outra coisa que não "o habitante do lugar x"?
- e em outras línguas, como demonyms funcionam? se funcionarem diferentemente do inglês, a formalização que o Adam propõe para demonyms funcionaria apenas para um tipo de uso destas palavras e não para seu uso mais geral.

**Comment by vcvpaiva** [comment]
Algumas correcoes na mensagem da Livy:
A frase em ingles nao precisa de ter ONE.

Tenho três amigos. O americano fala muito.
I have three friends. The american  talks a lot.
Valeria concorda que  "americano" nessa sentenca 'e substantivo, 'e o tal demonym do qual falamos.

se as sentencas fossem:
I have three cars. The Japanese is a gas-guzzler.
Eu tenho tres carros. O japones bebe muito.

o "japones" 'e uma elipse (ou metafora) pro "carro japones" onde Japanese 'e um adjetivo gentilico.

Eu concluo que gentílicos e demonyms funcionam da mesma forma em PT/EN sim.

>demonyms em PT poderiam significar outra coisa que não "o habitante do lugar x"
Nao, eu concordo com o Adam que esse 'e o significado  de demonym. 

O gentilico "japones/Japanese" pode funcionar como um substantivo (acho que eles chamam de "a nominal use of the adjective") na frase "o japones bebe muito" acima.  (qq pessoa normal pensaria que estavamos falando de sake e whisky japones, dada somente a segunda sentenca).

eu so conheco um pouquinho de frances, mas la' tb funciona que nem em ingles e portugues, pelo que eu me lembro.

**Comment by arademaker** [comment]
Livy, isto não é espaço para discussão. Ou temos algo concreto para ser feito em relação a OWN-PT ou não temos. Se desta discussão (que não deve ser feita aqui) não surgir nenhuma TASK especifica para ser feita (ex: correções nos dados, acrescimo de alguma flag etc) este issue deve ser fechado.

Vou fechar e vc reabre se surgirem sugestões de ATIVIDADES concretas a serem feitas.
