### ISSUE TITLE
Should not delete word when it is involved in a nomlex relation

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#102]
[ Placeholder issue, needs more careful analysis before implementation! ]

https://github.com/own-pt/wordnet-editor/blame/master/backend.lisp#L63

**Comment by fcbr** [comment]
Looking at the code, the word (`wn30:Word`) subject are only deleted if we **don't** specify a synset on the call to `REMOVE-WORD`, which doesn't happen on processing suggestions.  So this bug isn't triggered by processing suggestions.

**Comment by arademaker** [comment]
esse problema não é um problema nos dados. Pode ser um problema no códigos que mantemos ou venhamos a criar para manter a OWN-PT e OWN-EN, em outros repositórios.
