### ISSUE TITLE
A sentiment lexicon for portuguese natural language processing

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#105]
http://www.scielo.br/scielo.php?pid=S1984-63982013000400004&script=sci_arttext

Podemos verificar cobertura da OWN-PT para a lista de palavras no final do artigo. 

Valeria: dada a lista de palavras com pos verificasse se elas estao na OWN-PT e nos desse os links pras que estao--uma versao um pouquinho mais self-contained dos relatorios do Fabricio, seria uma mao-na-roda nao? isso seria muito dificil?

**Comment by livyreal** [comment]
A lista do artigo da Cláudia está limpa [aqui](https://github.com/livyreal/Senti_List_PT/tree/master).

Mantive a lista exatamente como o apêndice da Cláudia trazia.
Esta lista tem typos ("horroroza"), tem entradas com POS aparentemente erradas ("atuar = ADJ"), palavras que não parecem ter polaridade ("essa"), expressões não lematizadas ("gostinho", "pra", "gargalhadas"), expressões que misturam lemma e PoS ("valer cada N"), palavras com hífen que eventualmente vão aparecer sem hífen ("cabeça-dura"), palavras que eu confirmaria com a Cláudia ("repa"), expressões que poderiam ser simplificadas ("ser um balde de água fria" poderia ser apenas "balde de água fria"), expressões com () indicando possibilidades de uso ("ser(um)show").

Acho ótima a ideia de verificar na OWN-PT, mas precisamos uniformizar estes casos antes.

**Comment by arademaker** [comment]
vou fechar este issue. Segundo Claudia esta lista ainda precisa ser bastante refinada para eventualmente poder contribuir de alguma forma.
