### ISSUE TITLE
Multilingual Central Repository 3.0 (Release 2016)

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#123]
http://adimen.si.ehu.es/web/MCR 

> The MCR integrates in the same EuroWordNet framework wordnets from six different languages: English, Spanish, Catalan, Basque, Galician and Portuguese. The Inter-Lingual-Index (ILI) allows the connection from words in one language to equivalent translations in any of the other languages thanks to the automatically generated mappings among WordNet versions. The current ILI version corresponds to WordNet 3.0. Furthermore, the MCR is enriched with the semantically tagged glosses.

We can try to merge the Portuguese content with our OWN-PT: glosses, words and examples

**Comment by arademaker** [comment]
We are happy to announce the second release of the Multilingual Central
Repository (MCR 3.0). Details about the MCR, including distribution
licenses, online consultation and download can be found in this
address:

http://adimen.si.ehu.es/web/MCR

The main changes with respect to MCR3.0 (Release 2012) are described
in section 2 of:
http://adimen.si.ehu.es/web/files/mcr30/README-2016.txt

The MCR 3.0 is the result of the 5th Framework MEANING project
(IST-2001-34460) and Spanish government KNOW (TIN2006-15049-C03),
KNOW2 (TIN2009-14715-C04-01), SKaTer (TIN2012-38584-C06) and TUNER
(TIN2015-65308-C5) projects.

The MCR integrates in the same EuroWordNet framework wordnets from
six different languages: English, Spanish, Catalan, Basque, Galician
and Portuguese. The Inter-Lingual-Index (ILI) allows the connection
from words in one language to equivalent translations in any of the
other languages. The current ILI version corresponds to WordNet 3.0.
Furthermore, the MCR is enriched with the semantically tagged glosses:
http://wordnet.princeton.edu/glosstag.shtml

The MCR also integrates WordNet Domains, the Top Ontology, AdimenSUMO
ontology and a new version of the Basic Level Concepts. In that way,
the MCR constitutes a natural multilingual large-scale semantic
resource for a number of semantic processes that need large amount of
multilingual knowledge to be effective tools.

If you use the MCR, please refer to the following publication:

Gonzalez-Agirre A., Laparra E. and Rigau G. Multilingual Central
Repository version 3.0: upgrading a very large lexical knowledge
base. In Proceedings of the Sixth International Global WordNet
Conference (GWC’12). Matsue, Japan. January, 2012.

http://adimen.si.ehu.es/~rigau/publications/gwc12-glr.pdf

**Comment by arademaker** [comment]
A PULO já foi incorporada à OWN-PT.

**Comment by vcvpaiva** [comment]
hmm, nao sei disso nao. a OWN-PT foi incorporada a PULO, nao a conversa. faz uma diferenca grande
