### ISSUE TITLE
NLTK

### ISSUE THREAD

**Issue by pvcastro** [own-pt/openWordnet-PT#134]
Olá,

O OpenWordnet-PT é suportado em alguma biblioteca python, semelhante ao wordnet do NLTK? O de lá tem poucos lemmas e synsets, creio que o de vocês deva ser **bem** mais completo.

Obrigado!

**Comment by vcvpaiva** [comment]
Olá @pvcastro, obrigada pela mensagem simpatica! seria bem legal se o NLTK quissesse usar a gente como um dos modulos deles! como eles ja' usam o multi wordnet do Francis Bond, acredito que nao seria dificil, mas nos estamos mais interessados em usar (varios) modulos de sistemas diferentes, pra ver como e onde nos saimos melhor. ou pelo menos, assim me parece...

**Comment by pvcastro** [comment]
Olá @vcvpaiva ! 
Estou iniciando meus estudos com NLP e semântica, e estou enxergando que o OpenWordnet-PT seria um componente essencial para se ter desenvolver componentes de semântica para língua portuguesa. Estou trabalhando num produto que necessita de conceitos de NLP para proporcionar funções de busca semântica em um motor de busca. Estou vendo que é um universo muito amplo e complexo, e estou tendo dificuldades de enxergar um caminho. Você poderia me indicar como o OpenWordnet-PT poderia me ajudar nisso, onde ele se encaixaria nesta demanda? Estudei um pouco do wordnet do nltk ontem e vi que ele aparenta ter todas as relações de semântica que poderíamos esperar em um idioma, estou certo?
Obrigado!

**Comment by Vnicius** [comment]
Já está disponível. É só utilizar `lang=por` como parâmetro

**Comment by arademaker** [comment]
Sim @Vnicius , mas falta confirmar como a atualização é feita. Vide meu último comentário acima.

**Comment by versant2612** [comment]
Pelo blog do OMW a última versão seria: 2015-11-12 Release of OMW 1.4

**Comment by arademaker** [comment]
A release que será lançada nos próximos dias estará disponível na nova lib https://github.com/goodmami/wn

**Comment by arademaker** [comment]
See #168

**Comment by versant2612** [comment]
@arademaker obrigada!

**Comment by arademaker** [comment]
@FredsoNerd, waiting for the tutorial we agree you would prepare. I just created the  v1.0.0 release.

**Comment by arademaker** [comment]
Olá @pvcastro, @Vnicius e @versant2612, desculpe a demora em concluirmos este issue. Acabei de publicar agora a release v1.0.0 das nossas OWN-PT e OWN-EN. 

Esta release logo estará indexada na biblioteca https://wn.readthedocs.io/en/latest/  para download direto via o nome apenas `own-pt` ou `own-pt`.m ,as já pode ser usada diretamente se no download vcs indicarem a URL dos arquivos "tar.gz" da release. Esta é uma nova biblioteca Python para trabalhar com wordnets que foca no melhor suporte a wordnets em vários idiomas quando comparada com o suporte para wordnets existente na NLTK. 

Antes nossas wordnets eram distribuídas nesta biblioteca wn como parte da coleção de wordnets do Francis Bond, a http://compling.hss.ntu.edu.sg/omw/. Este esquema não nos dava controle para publicar nosso recurso independente das releases de OMW, por isso agora somos uma coleção independente. 

Finalmente, obviamente os dados podem ser usados diretamente sem a `wn` em qualquer outra linguagem de programação que os arquivos XML ou RDF possam ser lidos.

Vou fechar este issue, mas fico a disposição para dúvidas. Vamos tentar atualizar nosso https://github.com/own-pt/openWordnet-PT/wiki e qualquer dúvida nos ajudará a entender o que precisamos adicionar no wiki...

**Comment by arademaker** [comment]
Versão inicial https://github.com/own-pt/openWordnet-PT/wiki/WN-Package

**Comment by andregom** [comment]
> Já está disponível. É só utilizar `lang=por` como parâmetro

Olá, saberia dizer melhor como fazer isso?

Estou fazendo o seguinte:

nltk.download('wordnet')

from nltk.corpus import wordnet as wn

Gostaria de saber como e onde colocar o parâmetro.

**Comment by arademaker** [comment]
Olá Andre, 

Vc vai precisar fazer o download da omw do Francis Bond

> nltk.download('omw-1.4’)

Mas note que não tenho controle sobre as releases da OMW, logo não sei se ela está atualizada com nossa última versão da OpenWordnet-PT. Me avise se conseguir avançar com esta informação. Talvez seja interessante ler

https://www.nltk.org/howto/wordnet.html

Ab.,
Alexandre
