### ISSUE TITLE
sorting search results in web interface

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#145]
I was comparing the search results for `house` in the [PWN](http://wordnetweb.princeton.edu/perl/webwn?o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&s=house&i=0&h=00000000000000#c) and for `casa` in [OWN](http://wnpt.brlcloud.com/wn/search?term=casa), and thought that sorting the results by hypernymy might improve their presentation (i.e., when people lookup `casa` they are probably not looking for `dine_in, eat_in | comer em casa`, which is the first result). although a tweak in the Solr query might also yield better sorting.

**Comment by arademaker** [comment]
You can be more specific and ask for synsets with “casa” in the word_pt field of the synset 

http://wnpt.brlcloud.com/wn/search?term=word_pt%3Acasa

This will give you a list closer to the PWN result.

**Comment by odanoburu** [comment]
that's good to know, thanks! still, for non-advanced users it'd be nice to have this feature
