### ISSUE TITLE
Hiperônimos e hipônimos

### ISSUE THREAD

**Issue by erickrf** [own-pt/openWordnet-PT#148]
Não econtrei nenhum hiperônimo nem hipônimo na versão atual do `own-pt.nt`, mas vi que essas relações existem na base usada pelo AllegroGraph web. Isso é proposital? Pretendem incluir essas relações nas próximas versões?

**Comment by arademaker** [comment]
@erickrf os dados da OWN-PT devem ser 'mesclados' com os dados da PWN. Ou seja, mescle os arquivos wordnet-en.nt.gz e own-pt.nt.gz.

**Comment by arademaker** [comment]
Os synsets de OWN-PT, so far, são sempre 1-1 com os synsets de PWN. Estamos começando a criar novos synsets apenas agora. A principio, o plano seria manter 1-1 sugerindo novos synsets para o que seria uma PWN expanded. Ou dependendo do que acontecer com o ILI da GWA, https://github.com/globalwordnet/ili

**Comment by erickrf** [comment]
Ok, obrigado!
