### ISSUE TITLE
Lemmatizer to remove duplicates, plurals, capitalization variants?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/openWordnet-PT#15]
one more example synset
Synset 09637013-n
Portuguese 	afro-americano, Afro-americanos

**Comment by arademaker** [comment]
Possivelmente usando https://github.com/rikarudo/LemPORT ou FreeLing?

**Comment by arademaker** [comment]
Outra estratégia seria usar

```
select ?ss ?lf ?t
{
  ?ss wn30:containsWordSense/wn30:word ?w ;
      rdf:type wn30:AdjectiveSynset .
  ?w wn30:lexicalForm ?lf .
  filter( regex(?lf,".*s$") && regex(str(?ss),"br") )
}
```

Se #36 for executada antes. Mas teriamos depois que voltar com os dados de RDF para a base da interface.

**Comment by arademaker** [comment]
Claudia tb sugeriu:

Mando em anexo uma lista de N ou ADJ cujo lema tem -s. Ou seja, buscamos os N | ADJ que estão codificados com -s e, se estiverem nessa lista, mantemos. Os que não estiverem, ficam sem o -s.
Para garantir, damos uma olhada no que deve ficar sem o -s.
Faz sentido?
A lista vem de uma busca no corpus CHAVE, que é jornalístico e metade PT, metade BR, com quase 100 milhões de palavras. Pedi N ou ADJ que tivessem lema terminando em -s, e dei uma limpada rápida na mão.

**Comment by arademaker** [comment]
neste momento, vários destes problemas já foram corridos manualmente pela interface através de sugestões.
