### ISSUE TITLE
links to inexistent word senses

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#153]
demonstration query:

http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/%0ASELECT%20DISTINCT%20?wordSense%0A%20%20%20%20%20%20%20%20%7B%0A%09?a%20?b%20?wordSense%20.%0A%09FILTER%20regex(str(?wordSense),%20%22wordsense-%5B0-9%5D+-%5B%5Ea%5D%22)%0A%20%20%09FILTER%20NOT%20EXISTS%20%7B%20?synset%20wn30:containsWordSense%20?wordSense%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%20

similar to #151 , but this time the wordsenses were probably deleted and not misconverted.

**Comment by vcvpaiva** [comment]
only 8 cases, we might as well list them:
--
wn30pt:wordsense-07510348-n-1 this one should be the nominal of "assombrar", "assombracao" or haunting
wn30pt:wordsense-00846021-n-2
wn30pt:wordsense-05770926-n-3
wn30pt:wordsense-06765044-n-5
wn30pt:wordsense-05154908-n-2
wn30pt:wordsense-10053808-n-1
wn30pt:wordsense-09768830-n-1
wn30pt:wordsense-06879180-n-2

**Comment by vcvpaiva** [comment]
Bruno @odanoburu I think you mean inexistent, or non-extant. 
(Wiktionary says "inexistant " is obsolete, see https://en.wiktionary.org/wiki/inexistant)
But I do not think that "the wordsenses were probably deleted".
We have not finished the project on nominalizations.

**Comment by arademaker** [comment]
Correto , cuidado que podem ser dados das nominalizações. Sobre a query, sim também temos inconsistencias quanto a urn dos senses. alguns são blank nodes outros tem o sense no padrão esperado.  

De qq forma isto não será tão relevante no novo formato txt que estamos trabalhando em https://github.com/own-pt/own-en e https://github.com/own-pt/mill (strange name)

**Comment by odanoburu** [comment]
hum, okay, I'm sure I understand your point about nominalizations, so maybe by saying how we can fix this issue I'll get it.

> Sobre a query, sim também temos inconsistencias quanto a urn dos senses. alguns são blank nodes outros tem o sense no padrão esperado.

not sure I understand what you are referring to.

> De qq forma isto não será tão relevante no novo formato txt 

not for this issue indeed, but for examples like #151 where there are many errors we will want to perform the corrections automatically. 

> (strange name)

well, `mill` is to be a new `grind` program, and mill is both a synonym for a sense of grind and a prefix of Miller (George)

**Comment by odanoburu** [comment]
okay, by

> Sobre a query, sim também temos inconsistencias quanto a urn dos senses. alguns são blank nodes outros tem o sense no padrão esperado.

you mean cases like http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/node/_:b871D4C92x470392? if so I didn't get it because I don't see any case like this among the wordsenses mentioned in this issue. do we have an issue for this? what's the solution we're envisioning?

**Comment by arademaker** [comment]
see #168

**Comment by arademaker** [comment]
a query que abriu este issue é 

```
SELECT DISTINCT ?wordSense
        {
	?a ?b ?wordSense .
	FILTER regex(str(?wordSense), "wordsense-[0-9]+-[^a]")
  	FILTER NOT EXISTS { ?synset wn30:containsWordSense ?wordSense }
           
        } 
```

no RDF do branch pre-release nao retorna valor, estou fechando issue.
