### ISSUE TITLE
satellite adjectives with duplicate lexical ids

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#154]
satellite adjectives are all from the same lexicographer file, and are differentiated by the head words of their cluster, not by their lexical ids; however I don't see why they shouldn't have sequential lexical ids -- they all currently have the same lexical id of `0` (this is inherited from PWN 3.0).

this [query](http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/select%20?ws1%20?ws2%20?lf%0Awhere%20%7B%0A%20%20?ss1%20rdf:type%20wn30:AdjectiveSatelliteSynset%20.%0A%20%20?ss2%20rdf:type%20wn30:AdjectiveSatelliteSynset%20.%0A%20%20?ss1%20wn30:containsWordSense%20?ws1%20.%0A%20%20?ss2%20wn30:containsWordSense%20?ws2%20.%0A%20%20?ws1%20wn30:word%20?w1%20.%0A%20%20?ws2%20wn30:word%20?w2%20.%0A%20%20?w1%20wn30:lexicalForm%20?lf%20.%0A%20%20?w2%20wn30:lexicalForm%20?lf%20.%0A%20%20filter%20(?ws1%20!=%20?ws2)%0A%20%20%7D) highlights the issue:

```sparql
select ?ws1 ?ws2 ?lf
where {
  ?ss1 rdf:type wn30:AdjectiveSatelliteSynset .
  ?ss2 rdf:type wn30:AdjectiveSatelliteSynset .
  ?ss1 wn30:containsWordSense ?ws1 .
  ?ss2 wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w1 .
  ?ws2 wn30:word ?w2 .
  ?w1 wn30:lexicalForm ?lf .
  ?w2 wn30:lexicalForm ?lf .
  filter (?ws1 != ?ws2)
  }
```

**Comment by hmuniz** [comment]
The following script moves all satellite adjectives to `adjs.all` and fix the lexical ids.

``` python
from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDFS
from wn2text import sort_synsets  # wn2text  is defined at https://github.com/own-pt/mill
import click


@click.command()
@click.argument('rdf_file', type=click.Path(exists=True, dir_okay=False, resolve_path=True),
                required=True)
@click.argument('rdf_final', required=True)
@click.option('-f', '--rdf-file-format', 'rdf_file_format', type=click.STRING, default='nt', show_default=True,
              help="Type of RDF input file. Must be accepted by RDFlib.")
def main(rdf_file, rdf_file_format, rdf_final):
    wn30 = Namespace("https://w3id.org/own-pt/wn30/schema/")
    graph = Graph()
    graph.parse(rdf_file, format=rdf_file_format)

    # CREATE ADJS.ALL

    graph.update("""
    DELETE {?s wn30:lexicographerFile "adj.all"}
    INSERT {?s wn30:lexicographerFile "adjs.all" }
    WHERE {
    ?s a wn30:AdjectiveSatelliteSynset .
    }
    """, initNs={'wn30': wn30})

    # fix lexical ids
    synsets = graph.subjects(wn30['lexicographerFile'], Literal("adjs.all"))
    aux = {}
    for synset, sorted_word_senses in sort_synsets(graph, synsets):
        for ws in sorted_word_senses:
            label = graph.value(ws, RDFS.label)
            new_lexid = aux[label] = aux.get(label, -1) + 1
            graph.remove((ws, wn30.lexicalId, None))
            graph.add((ws, wn30.lexicalId, Literal(str(new_lexid))))

    graph.serialize(rdf_final, format="nt")


if __name__ == '__main__':
    main()
```
Runnig:
``` bash 
 python3 fix_adj.py wordnet-en-update.nt wordner-update.nt
```

**Comment by arademaker** [comment]
@FredsoNerd o que precisamos confirmar é se nada foi perdido do modelo de dados da PWN. Existem os sense keys, existem os adjs head e satélites. para alguns exemplos, podemos olhar como estão nos DBFiles e como está o RDF. Se confirmarmos que nada foi perdido, me parece que este issue é relevante apenas para o projeto MILL que eventualmente podemos considerar voltar a trabalhar no futuro.

**Comment by arademaker** [comment]
vamos fechar este issue por agora. depois de avaliarmos algumas vezes, entendemos que isto seria uma sugestão de mudança em relação ao modelo adotado por PWN mas que podemos reavaliar no futuro.
