### ISSUE TITLE
derivationallyRelated adjectives

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#155]
I think this issue might be already known, but...

this [query](http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/select%20?ss%20?wf%0Awhere%20%7B%0A%20%20?ss%20a%20wn30:AdjectiveSatelliteSynset%20.%0A%20%20?ss%20wn30:containsWordSense%20?wf%20.%0A%20%20?wf%20wn30:derivationallyRelated%20?_%20.%0A%20%20%7D) shows wordsenses of adjective satellite synsets that have the `derivationallyRelated` relation, which according to [PWN documentation](https://wordnet.princeton.edu/documentation/wninput5wn) should be restricted to nouns and verbs (this also happens for adjective synsets). but these exist in the PWN data, so I'm guessing it's a documentation bug.

**Comment by odanoburu** [comment]
there's also the case of `derivationallyRelated` relations in wordsenses of adverb synsets, of which there's only one in WN3.0, and a handful in WN3.1 -- which seems awfully inconsistent.

**Comment by arademaker** [comment]
No modelo que sugerimos em https://github.com/own-pt/openWordnet-PT/blob/master/wn30.ttl#L391-L395 isto já tinha sido identificado. 

Caso adv relatei nos meus slides na GWC 2019 . Penso que deveriam ser `adverbPertainsTo`. Em PWN 3.1 temos 6 casos

```
$ grep + data.adv | wc -l
       6
```

A questão é se corrigimos isso no RDF ou no TXT quando os dados forem produzidos.

**Comment by arademaker** [comment]
Em https://github.com/own-pt/openWordnet-PT/blob/df754c2e4ee72127553147f16d0d2fedd6b0a9fb/wn30.ttl#L391-L395, eu adaptei a wn30.ttl (nosso esquema de dados / Ontologia) para que a relação `derivationallyRelated` fosse entre os super tipos `WordSense`, ou seja, entre qualquer sense de qualquer POS. Na verdade, o melhor seria termos expressividade em OWL e RDF para  dependent types (poder dizer que se um link `derivationallyRelated` parte de um nome, deve ir para um verbo etc) mas não temos isso, por isso minha solução. 

Quanto aos dados, me parece que não temos razão para achar que eles estejam errados, a discussão aqui parece ser apenas sobre a modelagem do esquema dos dados.
