### ISSUE TITLE
rdf: wordsenses without words?

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#156]
see [query](http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/select%20distinct%20?ws%0Awhere%20%7B%0A%20%20%7B?ss%20owl:sameAs%20?_%7D%20UNION%20%7B?__%20owl:sameAs%20?ss%7D%20.%0A%20%20?ss%20wn30:containsWordSense%20?ws%20.%0A%20%20filter%20not%20exists%20%7B?ws%20wn30:word%20?word%7D%0A%20%20%7D).

**Comment by vcvpaiva** [comment]
are these coming from the nominalizations, perhaps?

**Comment by arademaker** [comment]
see #168

**Comment by arademaker** [comment]
a query que abriu este issue no novo RDF no branch pre-release ja não retorna valores.  A query é

```sparql
select distinct ?ws
where {
  {?ss owl:sameAs ?_} UNION {?__ owl:sameAs ?ss} .
  ?ss wn30:containsWordSense ?ws .
  filter not exists {?ws wn30:word ?word}
  }
```
