### ISSUE TITLE
rdf: lexicalForm in Portuguese uses spaces

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#157]
but in English they are substituted for underscores

**Comment by arademaker** [comment]
yep. we need to normalize it. During RDF generation, since we have explicit string delimitators, I believe we should replace underscore by spaces. But for the files...

**Comment by vcvpaiva** [comment]
why not keep the English, well-established, usage?

**Comment by arademaker** [comment]
well-established used in the dbfiles. XML files use spaces I believe.

**Comment by arademaker** [comment]
see #168

**Comment by arademaker** [comment]
De qq modo, para as words em PT, ou pelo menos para todas que foram marcadas com lang = PT, só usamos espaços:

```sparql
select *
{
  ?a wn30:lexicalForm ?lf .
  filter ( lang(?lf) = "pt" && regex(str(?lf),"[_]+","i") )
}
``` 

Esta query não retorna valores.

**Comment by arademaker** [comment]
lendo melhor, este issue foi aberto questionando o uso de espaços para words em PT. Neste contexto, vou fechar o issue porque decidimos sim usar espaço e não underscore. Mas como na https://github.com/globalwordnet/english-wordnet/blob/master/src/yaml/noun.time.yaml, acho que devemos também trocar as words em EN. O recurso de trocar espaços por underscore foi uma forma de encoding das informações no formato datasse files de PWN. Vou abrir outro issue relacionado.
