### ISSUE TITLE
Investigate the issue with PWN numbers

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#159]

**Comment by arademaker** [comment]
See https://github.com/own-pt/cl-wnbrowser/issues/103#issuecomment-105569359

**Comment by arademaker** [comment]
como preparação da release, vamos gerar uns arquivos com estatísticas sobre os arquivos RDF... e usando estas estatísticas podemos conferir esta suspeita de erro do link acima.

**Comment by arademaker** [comment]
no release, vamos ter um TXT com estatisticas da OWN-PT sendo distribuida, para começar podemos ter as tabelas abaixo:

```

       PWN 3.0  OWN-PT
Core   X1       Y1 = numero de X1 com pelo menos 1 palavra em PT
Base   X2       Y2 = idem


Noun   X3       Y3 = numero de X3 com pelo menos 1 palavra em PT
Verb   X4       ...
Adj    X5
Adv    X6


Polysemy in OWN-PT

      # words 1 sense     # words >1 sense
Noun
Verb
Adj
Adv

MWE in OWN-PT

       # mwe
Noun   ...
Verb   ...
Adj    ...
Adv    ...

```

**Comment by FredsoNerd** [comment]
As discussed before, follow the statistics tables. The queries are available at [own-en.rq](https://github.com/own-pt/py-ownpt/blob/0111cee67bd18db065692098e47486239a1b1cbe/sparql/own-en.rq) and [own-pt.qr](https://github.com/own-pt/py-ownpt/blob/0111cee67bd18db065692098e47486239a1b1cbe/sparql/own-pt.rq). Those were run in [AllegroGraph](https://allegrograph.com/) considering the data at 1a7e2159406520e61ad6643834202a4c4450a8f6

# Table of Contents

1.  [Base and Core Concepts](#org966beba)
2.  [Instantiated Synsets](#org8335859)
3.  [Polysemy OWN-EN](#orgc22f08a)
4.  [Polysemy OWN-PT](#org138f982)
5.  [Multi Word Expressions](#orgec7fa85)



<a id="org966beba"></a>

# Base and Core Concepts

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Synset Type</th>
<th scope="col" class="org-right">OWN-EN</th>
<th scope="col" class="org-right">OWN-PT</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">wn30:CoreConcept</td>
<td class="org-right">4960</td>
<td class="org-right">4959</td>
</tr>


<tr>
<td class="org-left">wn30:BaseConcept</td>
<td class="org-right">4683</td>
<td class="org-right">436</td>
</tr>
</tbody>
</table>


<a id="org8335859"></a>

# Instantiated Synsets

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Synset Type</th>
<th scope="col" class="org-right">OWN-EN</th>
<th scope="col" class="org-right">OWN-PT</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">wn30:NounSynset</td>
<td class="org-right">82115</td>
<td class="org-right">35522</td>
</tr>


<tr>
<td class="org-left">wn30:VerbSynset</td>
<td class="org-right">13767</td>
<td class="org-right">8186</td>
</tr>


<tr>
<td class="org-left">wn30:AdverbSynset</td>
<td class="org-right">3621</td>
<td class="org-right">1966</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSynset</td>
<td class="org-right">7463</td>
<td class="org-right">3335</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSatelliteSynset</td>
<td class="org-right">10693</td>
<td class="org-right">3570</td>
</tr>
</tbody>

<tbody>
<tr>
<td class="org-left">wn30:Synset</td>
<td class="org-right">17659</td>
<td class="org-right">525</td>
</tr>
</tbody>
</table>


<a id="orgc22f08a"></a>

# Polysemy OWN-EN

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Synset Type</th>
<th scope="col" class="org-right">1 Word</th>
<th scope="col" class="org-right">+ Words</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">wn30:NounSynset</td>
<td class="org-right">42054</td>
<td class="org-right">40061</td>
</tr>


<tr>
<td class="org-left">wn30:VerbSynset</td>
<td class="org-right">8041</td>
<td class="org-right">5726</td>
</tr>


<tr>
<td class="org-left">wn30:AdverbSynset</td>
<td class="org-right">2400</td>
<td class="org-right">1221</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSynset</td>
<td class="org-right">5690</td>
<td class="org-right">1773</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSatelliteSynset</td>
<td class="org-right">5663</td>
<td class="org-right">5030</td>
</tr>
</tbody>

<tbody>
<tr>
<td class="org-left">wn30:Synset</td>
<td class="org-right">63848</td>
<td class="org-right">53811</td>
</tr>
</tbody>
</table>


<a id="org138f982"></a>

# Polysemy OWN-PT

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Synset Type</th>
<th scope="col" class="org-right">1 Word</th>
<th scope="col" class="org-right">+ Words</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">wn30:NounSynset</td>
<td class="org-right">21523</td>
<td class="org-right">13999</td>
</tr>


<tr>
<td class="org-left">wn30:VerbSynset</td>
<td class="org-right">4571</td>
<td class="org-right">3615</td>
</tr>


<tr>
<td class="org-left">wn30:AdverbSynset</td>
<td class="org-right">1219</td>
<td class="org-right">747</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSynset</td>
<td class="org-right">2462</td>
<td class="org-right">873</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSatelliteSynset</td>
<td class="org-right">2265</td>
<td class="org-right">1305</td>
</tr>
</tbody>

<tbody>
<tr>
<td class="org-left">wn30:Synset</td>
<td class="org-right">32040</td>
<td class="org-right">20539</td>
</tr>
</tbody>
</table>


<a id="orgec7fa85"></a>

# Multi Word Expressions

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Synset Type</th>
<th scope="col" class="org-right">OWN-EN</th>
<th scope="col" class="org-right">OWN-PT</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">wn30:NounSynset</td>
<td class="org-right">60344</td>
<td class="org-right">14747</td>
</tr>


<tr>
<td class="org-left">wn30:VerbSynset</td>
<td class="org-right">2829</td>
<td class="org-right">824</td>
</tr>


<tr>
<td class="org-left">wn30:AdverbSynset</td>
<td class="org-right">714</td>
<td class="org-right">598</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSynset</td>
<td class="org-right">65</td>
<td class="org-right">200</td>
</tr>


<tr>
<td class="org-left">wn30:AdjectiveSatelliteSynset</td>
<td class="org-right">434</td>
<td class="org-right">368</td>
</tr>
</tbody>

<tbody>
<tr>
<td class="org-left">wn30:Synset</td>
<td class="org-right">64243</td>
<td class="org-right">16684</td>
</tr>
</tbody>
</table>

**Comment by FredsoNerd** [comment]
In Valeria's comment, https://github.com/own-pt/cl-wnbrowser/issues/103#issuecomment-105569359, she discusses about some data differing from original PWN. For instances: PWN has 118695 synsets (in OWN-EN we found 117659); PWN has 97329 monossemic synsets (in OWN-EN we found 63.848).

But in in the data from http://wordnetcode.princeton.edu/3.0/WNdb-3.0.tar.gz, and in http://compling.hss.ntu.edu.sg/omw/, I found 117659 defined Synsets, and 206978 WordSenses. Exactly same numbers found in OWN-EN.

**Comment by FredsoNerd** [comment]
Statistics in format from http://compling.hss.ntu.edu.sg/omw/. The percentages consider the Cores defined in http://compling.hss.ntu.edu.sg/omw/wn30-core-synsets.tab, with a total of 1960 Core

# Open Multilingual Wordnet

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Wordnet</th>
<th scope="col" class="org-left">Lang</th>
<th scope="col" class="org-right">Synsets</th>
<th scope="col" class="org-right">Words</th>
<th scope="col" class="org-right">Senses</th>
<th scope="col" class="org-right">Core</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">OWN-PT</td>
<td class="org-left">pt</td>
<td class="org-right">52579</td>
<td class="org-right">57354</td>
<td class="org-right">83768</td>
<td class="org-right">4959 (99,98%)</td>
</tr>


<tr>
<td class="org-left">OWN-EN</td>
<td class="org-left">en</td>
<td class="org-right">117659</td>
<td class="org-right">156584</td>
<td class="org-right">206978</td>
<td class="org-right">4960 (100%)</td>
</tr>
</tbody>
</table>


PS: the single Synset not defined with Sense in OWN-PT, is the **01233027-v**

**Comment by arademaker** [comment]
Please close this issue by documenting the code I need to execute to populate the `statistics.org` file.

**Comment by FredsoNerd** [comment]
In f285c4a5b48b3150188ae1dcb25d0000eabcd06b, we populate a statistics.org file, generated by [this script](https://github.com/own-pt/py-ownpt/blob/f5652fddd42565b38f34a5f5ab38c956e92339c6/pyownpt/cli/generate_statistics.py.). One might run it as follows:

```console
python3 generate_statistics.py --ownpt openWordnet-PT/data/own-pt-* --ownen openWordnet-PT/data/own-en-* -vv
```

**Comment by arademaker** [comment]
Second link is not working

**Comment by FredsoNerd** [comment]
Sure. It looks like I added a dot after the link. I've just edited the previous comment with the right link:

https://github.com/own-pt/py-ownpt/blob/f5652fddd42565b38f34a5f5ab38c956e92339c6/pyownpt/cli/generate_statistics.py
