### ISSUE TITLE
multiple lexical_forms to  a word

### ISSUE THREAD

**Issue by odanoburu** [own-pt/openWordnet-PT#163]
see [query](http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/select%20*%20where%0A%7B%0A%20%20?w%20ns1:lexicalForm%20?lf1%20.%0A%20%20?w%20ns1:lexicalForm%20?lf2%20.%0A%20%20filter%20(?lf1%20!=%20?lf2)%0A%7D)

the cases I've seen seem to be spaces vs. underline and spaces vs. hyphen.

**Comment by arademaker** [comment]
see #168

**Comment by arademaker** [comment]
No último RDF no branch pre-release a query acima (reproduzida abaixo), não retorna valores, problema resolvido.

```sparql
select * where
{
  ?w wn30:lexicalForm ?lf1 .
  ?w wn30:lexicalForm ?lf2 .
  filter (?lf1 != ?lf2)
}
```
