### ISSUE TITLE
List of 'gold' reference dictionaries 

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/openWordnet-PT#164]
Learning from the EWN experience:
1.https://houaiss.uol.com.br/pub/apps/www/v5-1/html/index.php#0 Houaiss
2.http://www.aulete.com.br/ Caldas Aulete
3.https://dicionario.priberam.org/ Priberam
4.https://michaelis.uol.com.br/busca?id=OWQE Michaelis

I have not found a free Aurelio. Do we need more sources?

**Comment by arademaker** [comment]
We need to find a better place to this list. for now, I will but them in the wiki. For the future, we need to discuss next steps with the idea of https://github.com/own-pt/own-en and https://github.com/own-pt/own-pt repositories

**Comment by arademaker** [comment]
added https://github.com/own-pt/openWordnet-PT/wiki/Online-references. Contributions will be welcome.
