### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#168]
1. update the RDFs with the pending votes/suggestions from the web interface
2. make a release
3. make it part of https://github.com/goodmami/wn/issues/97

some other issues may be related to it such as 

1. https://github.com/own-pt/openWordnet-PT/issues/136
2. https://github.com/own-pt/openWordnet-PT/issues/112

e outros...

**Comment by arademaker** [comment]
1. entrada é no formato JSON do Elastic Search (dump)
2. saida é JSON-LD 
3. ao processar entrada, precisamos aplicar votos/suggestões antes de converter

**Comment by goodmami** [comment]
If you wish to distribute your release on GitHub, I recommend setting up a GitHub Action that does the following when a new [release in GitHub](https://github.com/own-pt/openWordnet-PT/releases) is created:
* validates the lexicon
* creates the [WN-LMF package](https://wn.readthedocs.io/en/latest/guides/lexicons.html#wn-lmf-files-packages-and-collections)
* compresses the package
* uploads the package as a release asset

See [OdeNet's workflow](https://github.com/hdaSprachtechnologie/odenet/blob/master/.github/workflows/release.yml) for an example. And I'm happy to answer questions about it.

**Comment by arademaker** [comment]
Thank you @goodmami !!

**Comment by arademaker** [comment]
eventually https://github.com/RDFLib/pySHACL

**Comment by arademaker** [comment]
preparing to automate the release, we need a script that:

1. update the RDF files from the dump folder
2. update the statistics.org with the new RDF content
3. generate a new XML LMF file

With that in place, we can make a new release and attach the XML LMF file to it.

**Comment by arademaker** [comment]
We need also to notify https://github.com/bond-lab/omw-data/issues/6 once the release is ready.

**Comment by arademaker** [comment]
@vcvpaiva to make a GitHub release of OWN-PT, I am planning to use the https://semver.org schema. But should we start as 1.0.0? It is strange to have a 1.0.0 version for a 10 years-old project...

**Comment by arademaker** [comment]
This is not what we want, but for now, we depend on https://github.com/own-pt/py-ownpt. Nevertheless, the code `update_ownpt.py` must be robust to correctly handle any new dump from the http://openwordnet-pt.org backend.

**Comment by FredsoNerd** [comment]
In fact, at this point, we are able to update, and generate new LMFs from https://github.com/own-pt/py-ownpt. After that, we should be able to discuss new environment for developing the data.

**Comment by vcvpaiva** [comment]
> @vcvpaiva to make a GitHub release of OWN-PT, I am planning to use the https://semver.org schema. But should we start as 1.0.0? It is strange to have a 1.0.0 version for a 10 years-old project...

I don't think it's strange, we had a different kind of indexing before (one that didn't update!) This is great news, thanks for all the work!!!!

**Comment by arademaker** [comment]
We found 3 or 4 rdfs:label in words.ttl , this looks like something that we forgot to clean.

**Comment by arademaker** [comment]
I could not install the the lib for making the XML. See https://github.com/own-pt/py-ownpt/issues/13. The lib should be named own lib or something similar, it works not only with PT data.

In the last XML I have, from August, the DTD in the header is 

``//globalwordnet.github.io/schemas/WN-LMF-1.0.dtd``

We want to follow DTD 1.1 right? Version should match the semantic versions 1.0.0 (same of the release). Email is my gmail 

```
  <Lexicon id="own-en" label="OpenWordnet-EN" status="checked" version="1.0.0" language="en" confidenceScore="1.0" url="http://openwordnet-pt.org/" email="..." license="http://creativecommons.org/licenses/by/4.0/" citation="http://arademaker.github.io/bibliography/coling2012.html">
```

**Comment by arademaker** [comment]
In the release.sh, why I can't see commands to produce the EN data from the dump? In the near future, We may change EN data in the dump.

**Comment by FredsoNerd** [comment]
> In the last XML I have, from August, the DTD in the header is
> 
> `//globalwordnet.github.io/schemas/WN-LMF-1.0.dtd`
> 
> We want to follow DTD 1.1 right? Version should match the semantic versions 1.0.0 (same of the release). Email is my gmail

Right. I updated those options in https://github.com/own-pt/py-ownpt/commit/7c73c29546d4e7a3b675c898fa5ae2f64fa2f425

**Comment by FredsoNerd** [comment]
> The lib should be named own lib or something similar, it works not only with PT data.

@arademaker , I've changed the project name and configurations to avoid this, now using the name `py-own`. Only the repo name in https://github.com/own-pt/py-ownpt should be replaced, but I have no right to do so.

**Comment by arademaker** [comment]
- [ ] move release.sh to this repo
- [ ] add XML validation

**Comment by goodmami** [comment]
Regarding the GitHub Action I recommended [above](https://github.com/own-pt/openWordnet-PT/issues/168#issuecomment-819198128), we recently had an issue with OdeNet where a minor problem prevented the release artifact from being uploaded (see https://github.com/hdaSprachtechnologie/odenet/issues/25). There was in fact a problem with the release so it was working correctly, but the resolution required us to delete the release tag and try again, so I think the process could be improved. If you go with this method, you might have one action for validation which runs on some action before a release, like a pre-release, a merged branch, or maybe on every commit. If this passes (including checking that the `version` attribute is appropriately updated), you can feel more confident in publishing the release and generating the artifacts.

**Comment by arademaker** [comment]
@goodmami , thank you. I am still trying to learn about GitHub actions. For this release, we did the additional asset (the XML files) manually.

**Comment by goodmami** [comment]
> can you check the package, if that is ok for your library wn?

Yes, I have reviewed it and am writing up a reply. Will be posted soon in goodmami/wn#97.

**Comment by arademaker** [comment]
release v1.0.0 was published.
