### ISSUE TITLE
lexicalForms em EN: trocar underscore por espaços

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#169]
Como consequencia de #157

**Comment by FredsoNerd** [comment]
see https://github.com/own-pt/py-ownpt/issues/7, more especifically this comment https://github.com/own-pt/py-ownpt/issues/7#issuecomment-901269406.

For certainty, one is able to simply check that the command will return nothing at  dd343c28205c5fa2ef84a5679234bfe761c9c9b0:
```
grep "_" openWordnet-PT/data/own-en-words.ttl
```
