### ISSUE TITLE
lemma property

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#170]
We found wordsenses and words with lemma

```
select *
{
  ?a wn30:lemma ?v1 .
  ?a rdfs:label ?v2 .
  filter (?v1 != ?v2) 
}
```

and 

```
select *
{
  ?a wn30:lemma ?v1 .
  ?a wn30:lexicalForm ?v2 .
  filter (?v1 != ?v2) 
}
```

1. toda word/wordsense em EN tem lemma? 
2. quais as diferenças entre lemma e lexicalForm  e lemma/label ? apenas upcase?

**Comment by arademaker** [comment]
considerando que a consulta abaixo não trouxe resultado, 

```
select *
{
  ?a wn30:lemma ?v1 .
  ?a wn30:lexicalForm ?v2 .
  filter (lcase(?v1) != lcase(?v2) )
}
```

podemos apagar todos as triplas do predicado `wn30:lemma` que ocorre em wordsenses e words.

**Comment by FredsoNerd** [comment]
Em 4ee848e removemos os `lemmas` através de uma ação de reparação. Ver #171 e https://github.com/FredsoNerd/py-ownpt/blob/3ab0a5ac80ed988da4a3eeecd21f9b958832f174/pyownpt/repair.py#L62-L74
