### ISSUE TITLE
AdjectiveSatelliteSynset with URIs using a 

### ISSUE THREAD

**Issue by FredsoNerd** [own-pt/openWordnet-PT#176]
In the past, for some reason, the URIs of `AdjectiveSatelliteSynset`, of the form `xxxxxxxx-s` were replaced by URIs of the form `xxxxxxxx-a`. We should bring back the `xxxxxxxx-s` format for consistency with the Synset property `ss_type` from https://wordnet.princeton.edu/documentation/prologdb5wn, avoiding confusions with the Words property `pos`.

The `AdjectiveSatelliteSynset` `<https://w3id.org/own-pt/wn30-en/instances/synset-00613866-a>` should have it's URI replaced by `<https://w3id.org/own-pt/wn30-en/instances/synset-00613866-s>`, for instance.

**Comment by FredsoNerd** [comment]
In bb56067955852830659182b786bd02ef4a7d976c, we replace URIs of AdjectiveSateliteSynsets in format `xxxxxx-a`, as discussed before, through [this script](https://github.com/own-pt/py-ownpt/blob/84c8afe81f9f0526846279fbdd89534fde6cd197/pyownpt/cli/adjective_satelites_uris.py).

The running and outputs for OWN-PT and OWN-EN:

```console
python3 pyownpt/cli/adjective_satelites_uris.py openWordnet-PT/own-files/own-en-* -l en -o own-en.nt -v
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-morphosemantic-links.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-relations.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-synsets.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-wordsenses.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-words.ttl'
INFO:ownpt:start formatting AdjectiveSatelliteSynset
INFO:ownpt:action applied to 10693 valid synsets
	total: 96700 triples added
	total: 96700 triples removed
INFO:root:serializing output to 'own-en.nt'
```

```console
python3 pyownpt/cli/adjective_satelites_uris.py openWordnet-PT/own-files/own-pt-* -l pt -o own-pt.nt -v
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-morphosemantic-links.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-relations.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-same-as.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-synsets.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-wordsenses.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-words.ttl'
INFO:ownpt:start formatting AdjectiveSatelliteSynset
INFO:ownpt:action applied to 0 valid synsets
	total: 0 triples added
	total: 0 triples removed
INFO:root:serializing output to 'own-pt.nt'
```

**Comment by arademaker** [comment]
This issue is related to #180 right? Do this last comment and the commit close this issue?

**Comment by arademaker** [comment]
What is the dev-pre-release branch? This can go quickly crazy. A branch of a branch of work.. please consider merging it into the pre-prelease branch as soon as possible.

**Comment by FredsoNerd** [comment]
> This issue is related to #180 right? Do this last comment and the commit close this issue?

I'd rather close #180 first, run again the action renaming AdjectiveSateliteSynset URIs, since the same problem is going to occur in OWN-PT files.

**Comment by FredsoNerd** [comment]
> What is the dev-pre-release branch? This can go quickly crazy. A branch of a branch of work.. please consider merging it into the pre-prelease branch as soon as possible.

I'm closing that branch; the only relevant changes are going to be subscribed by new actions after repeating some steps because #180. I think this way we'll avoid confusion. New changes are going directly to pre-release.

**Comment by FredsoNerd** [comment]
In a0523a9be3d44cef9ec253ffdef63fd01e1f9296 and d0db9cff61747a231aaef00d6163a7a85b3690b8, we fix this problem. As said before, we ran the scripts again:

```console
python3 adjective_satelites_uris.py own-files/own-en-* own-files/own-pt-same-as.ttl -l en -o own-en.nt -v
INFO:root:loading data from file 'own-files/own-en-morphosemantic-links.ttl'
INFO:root:loading data from file 'own-files/own-en-relations.ttl'
INFO:root:loading data from file 'own-files/own-en-synsets.ttl'
INFO:root:loading data from file 'own-files/own-en-wordsenses.ttl'
INFO:root:loading data from file 'own-files/own-en-words.ttl'
INFO:root:loading data from file 'own-files/own-pt-same-as.ttl'
INFO:ownpt:start formatting AdjectiveSatelliteSynset
INFO:ownpt:action applied to 10693 valid synsets
	total: 118086 triples added
	total: 118086 triples removed
INFO:root:serializing output to 'own-en.nt'
```

```console
python3 adjective_satelites_uris.py own-files/own-pt-* -l pt -o own-pt.nt -v
INFO:root:loading data from file 'own-files/own-pt-morphosemantic-links.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-relations.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-same-as.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-synsets.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-wordsenses.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-words.ttl'
INFO:ownpt:start formatting AdjectiveSatelliteSynset
INFO:ownpt:action applied to 10693 valid synsets
	total: 82512 triples added
	total: 82512 triples removed
INFO:root:serializing output to 'own-pt.nt'
```
