### ISSUE TITLE
AdjectiveSynsets sameAs AdejctiveSateliteSynsets

### ISSUE THREAD

**Issue by FredsoNerd** [own-pt/openWordnet-PT#180]
In OWN-PT, we have no instances of `AdjectiveSatelliteSynsets`, even for those synsets wich are `sameAs` some `AdjectiveSateliteSynsets`. In these cases they appear as `AdjectiveSynsets`.

For instance,
```
<https://w3id.org/own-pt/wn30-en/instances/synset-02598110-s> owl:sameAs <https://w3id.org/own-pt/wn30-pt/instances/synset-02598110-a>
```
Here, `synset-02598110-s` is `AdjectiveSatelliteSynsets`, but `synset-02598110-a` is `AdjectiveSynsets`.

**Comment by arademaker** [comment]
We need to fix that. So far, OWN-PT is not expected to introduce ANY structural change in the OWN-EN network. Of course, the OWN-EN itself is, so far, just an RDF version of PWN 3.0.

**Comment by FredsoNerd** [comment]
Synce we have synset relations from OWN-EN projected in OWN-PT, the natural solution is to change the types in those cases. In fact, those synsets _act_ topologically as satellites. I'm doing so.

**Comment by arademaker** [comment]
Yes, that is what I said. The type and the URI os the synsets in OWN-PT should follow the structure of OWN-EN/PWN30

**Comment by FredsoNerd** [comment]
In 750d92ea7f8f4ed559977c52e9c8cdda6e81765c we fix that problem, through [adjective_satelites_sameas](https://github.com/own-pt/py-ownpt/blob/b962a3e09f7a4d8026c6ac529dab9dd3554adeb2/pyownpt/cli/adjective_satelites_sameas.py), responsible for reviewing those types, as discussed before. The running and outputs:
```console
python3 pyownpt/cli/adjective_satelites_sameas.py own-pt-synsets.ttl openWordnet-PT/own-files/own-en-synsets.ttl openWordnet-PT/own-files/own-pt-same-as.ttl -o own-pt-synsets.ttl -v
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-synsets.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-en-synsets.ttl'
INFO:root:loading data from file 'openWordnet-PT/own-files/own-pt-same-as.ttl'
INFO:ownpt:start formatting AdjectiveSatelliteSynset
INFO:ownpt:action applied to 10693 synsets
	total: 10693 triples added
	total: 10693 triples removed
INFO:root:serializing output to 'own-pt-synsets.ttl'
```

**Comment by arademaker** [comment]
The command interface for `pyownpt/cli/adjective_satelites_sameas.py` is weired, I would expect a single RDF as input or a directory. It is complicate to specify in each steps the specific fragments of the data that one needs.

**Comment by arademaker** [comment]
I was not able to check the changes, but I suppose for each adj synset (18156+10693 according to http://wn.mybluemix.net/search?search_field=all&term=), we should have added the right type and removed the wrong one, and changed the URI. So the numbers above are strange. I would expect more changes since the new URI would force more changes in more triples.

**Comment by FredsoNerd** [comment]
In fact, in this specific case, we deal only with type definitions considering the relations of `OWL:sameAs`, so that no URI needs to be replaced globally. This is why we need only those 3 files.

In that case, the lines changed are from `own-pt-synsets` projecting the types AdjectiveSateliteSynsets from OWN-EN. This is why exactly 10693 synsets, from OWN-PT, are changed.

**Comment by FredsoNerd** [comment]
> we should have added the right type and removed the wrong one, and changed the URI

For modularity, we maintain the problem of redefining the URIs to #176
