### ISSUE TITLE
update schema uri

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#188]
At https://w3id.org

**Comment by arademaker** [comment]
https://github.com/perma-id/w3id.org/pull/2330

**Comment by arademaker** [comment]
See b9a518f1a3f25ea70b793f8b1550b5a6c4d6b47a

**Comment by FredsoNerd** [comment]
see https://github.com/own-pt/openWordnet-PT/issues/70#issuecomment-922154793 or a479a97398ac91dc98e77f6067420b5524c8e47c.

I think that it it. Is there anything else to be done about the new schemas, @arademaker ?
