### ISSUE TITLE
Rename Schemas

### ISSUE THREAD

**Issue by FredsoNerd** [own-pt/openWordnet-PT#190]
In https://github.com/own-pt/openWordnet-PT/issues/70, we discuss some URIs, in special the necessity of replacing old schema URIs. Once we changed the schemas, we got the definitions:

```xml 
<https://w3id.org/own/own-pt/instances/> a skos:ConceptScheme ;
    dc:title "Brazilian Portuguese Wordnet" .
```
```xml
<https://w3id.org/own/own-en/instances/> a skos:ConceptScheme ;
    dc:title "Princeton Wordnet 3.0" .
```
Doesn't make sense tho change the names, specially in the case of OWN-EN, wich is now understood to be not `Princeton Wordnet`, but `Open Wordnet English`, in a independent way?

@arademaker ?

**Comment by arademaker** [comment]
Yes, both names need to be changed:

1. "Brazilian Portuguese Wordnet" ~> "Open Wordnet for Portuguese"
2. "Princeton Wordnet 3.0" ~> "Open Wordnet for English (Forked from Princeton Wordnet 3.0)"

**Comment by FredsoNerd** [comment]
We did so manually in f9248c4259f47ce41405713a1ff6e5ea922ee218.
