### ISSUE TITLE
gerar novo arquivo RDF

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#36]
1. gerar novo RDF
2. renomear blank nodes (words e wordsenses)
3. corrigir nome de word nodes que estão com wordXXXX e não word-XXXX onde XXXX é a forma léxica da palavra com espaços trocados por underscore.

**Comment by fcbr** [comment]
Bom, ja' geramos varios RDF desde que esta issue foi aberta.  Fechando.  Podemos pensar num esquema de release engineering para o futuro.
