### ISSUE TITLE
[verification] skos#inScheme is wrong

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#65]
skos#inScheme has range ConceptScheme, but we are using literals, according to RDFUnit (which doesn't seem to be the case).  I'm not sure what is wrong here.  Need to investigate what is the issue that RDFUnit found.

**Comment by arademaker** [comment]
Literals? Not in the triplestore:

http://wnpt.brlcloud.com:10035/repositories/wn30#node/%3Chttp://www.w3.org/2004/02/skos/core%23ConceptScheme%3E

**Comment by fcbr** [comment]
Might be an RDFUnit issue.
