### ISSUE TITLE
[verification] pellet lint: untyped classes

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#66]
pellet lint found the following untyped classes:

[Untyped classes]
- https://w3id.org/own-pt/nomlex/schema/ResultNominalization
- https://w3id.org/own-pt/wn30/schema/BaseConcept
- https://w3id.org/own-pt/nomlex/schema/Animate
- https://w3id.org/own-pt/nomlex/schema/EventNominalization
- https://w3id.org/own-pt/nomlex/schema/Deverbal
- https://w3id.org/own-pt/nomlex/schema/Lexicalized
- https://w3id.org/own-pt/nomlex/schema/Nominalization
- https://w3id.org/own-pt/wn30/schema/CoreConcept
- https://w3id.org/own-pt/nomlex/schema/Agentive
- http://www.w3.org/2004/02/skos/core#ConceptScheme

**Comment by arademaker** [comment]
What is an untyped class?

**Comment by fcbr** [comment]
Look at https://w3id.org/own-pt/nomlex/schema/ResultNominalization

We use it as a type but there is no definition of what https://w3id.org/own-pt/nomlex/schema/ResultNominalization is.  I think that's what it is calling an "untyped class".

**Comment by arademaker** [comment]
done
