### ISSUE TITLE
[verification] Need to review all IRIs

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#70]
We probably should keep them plain ASCII to avoid any possible encoding issues between different systems and file formats.

**Comment by arademaker** [comment]
Nós agora usamos `+` para words com espaços.

**Comment by arademaker** [comment]
In the LMF generation, we had to deal with the ID datatype of XML. See https://en.wikipedia.org/wiki/Document_type_definition e https://www.w3.org/TR/REC-xml/#id

So far, we didn't pay attention to that, and URIs of words in the RDF files can contain `/` and accents. But this must be more robust. 

@gdemelo had some links about how he implemented it in lexvo:

> The Java API described at http://lexvo.org/linkeddata/tutorial.html includes a function to create such term URIs. The .jar file can be opened and includes source code in Java. Or you could use it in Clojure.

In Python, we can eventually use an already standard library for url encoding?! 

We expect that words should have final encode like below for RDF and XML:

```
<https://w3id.org/own-pt/wn30-pt/instances/word-TCP%2FIP-n>
```

```
<LexicalEntry id="word-TCP%2FIP-n”>
 <Lemma partOfSpeech="n" writtenForm="TCP/IP”/>
 <Sense id="own-pt-wordsense-06666486-n-3" synset="own-pt-synset-06666486-n"/>
</LexicalEntry>
```

**Comment by arademaker** [comment]
Note that words may contain `-`, how the encode would deal with that? One possible solution for not confuse with the pos tagger is to transform the pattern `word-ELS-pos`  to `word-pos-EFS` where ELS  is 'encoded lexical form`.

**Comment by arademaker** [comment]
https://github.com/globalwordnet/schemas/issues/55

Let us wait 1-2 days for some feedback.

**Comment by FredsoNerd** [comment]
As well discussed in the issue referenced before, one of the more readable and natural ways to solve our problem is to consider quoting the not xml:ID valid characters/forms, such as `comma replaced with -cm-`, and `apostrophe replaced with -ap-`. Whenever impossible to have a name mapping, a final option is to replace with hexadecimal encoding.

A first approach is to think about mapping characters into HTML entity names, which is well documented mapping. I found a first smaller table for HTML Entity Names (Latin-1), manually scraped from https://cs.stanford.edu/people/miles/iso8859.html. The rule was:

 1. replace spaces by underlines
 2. if _CHAR_ is valid to compose DTD ID, let it be
 3. if _CHAR_ is invalid to compose DTD ID, try to replace by -NAME-
 4. if _CHAR_ is invalid to compose DTD ID and there is no name, replace by -HEX-

This way we got some reasonable, expected IDs:
 - "(militar) ocupação": `own-pt-word--lpar-militar-rpar-_ocupação-n`
 - "Território do Norte": `own-pt-word-Território_do_Norte-n`

Only two Lexical Entries had characters replaced by Hexadecimal Forms:
```xml
    <LexicalEntry id="own-pt-word-vapor_d-e28099-água">
      <Lemma partOfSpeech="n" writtenForm="vapor d’água"/>
      <Sense id="own-pt-wordsense-15055442-n-3" synset="own-pt-synset-15055442-n"/>
    </LexicalEntry>
    <LexicalEntry id="own-pt-word-Sacro_Império_Romano-e28093-Germânico">
      <Lemma partOfSpeech="n" writtenForm="Sacro Império Romano–Germânico"/>
      <Sense id="own-pt-wordsense-08169677-n-2" synset="own-pt-synset-08169677-n"/>
    </LexicalEntry>
```

**Comment by FredsoNerd** [comment]
Another possible approach to avoid this scrapping and use a more robust table is to use the unicode entity names from HTML5, already implemented in https://docs.python.org/3/library/html.entities.html, based on https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references.

One may notice that many characters have multiple names, such as `-` (`hyphen;` or `ETH`). This is intentional, and some decision has to be made in our purpose: consider the first in lexicographical sorting, for instance.

Currently working into that.

**Comment by FredsoNerd** [comment]
In https://github.com/own-pt/py-ownpt/commit/0cbe46bde68b9eb43f5dc5899c2db8754ded6392, we implement the solution described before, obtaining the desirable results, such as follows:

```xml
    <LexicalEntry id="own-pt-word--lpar-de-rpar-_tempo_parcial-a">
      <Lemma partOfSpeech="a" writtenForm="(de) tempo parcial"/>
      <Sense id="own-pt-wordsense-01089369-a-1" synset="own-pt-synset-01089369-a"/>
    </LexicalEntry>
    ....
    <LexicalEntry id="own-pt-word-Sacro_Império_Romano-ndash-Germânico-n">
      <Lemma partOfSpeech="n" writtenForm="Sacro Império Romano–Germânico"/>
      <Sense id="own-pt-wordsense-08169677-n-2" synset="own-pt-synset-08169677-n"/>
    </LexicalEntry>
    ...
    <LexicalEntry id="own-pt-word-vapor_d-CloseCurlyQuote-água-n">
      <Lemma partOfSpeech="n" writtenForm="vapor d’água"/>
      <Sense id="own-pt-wordsense-15055442-n-3" synset="own-pt-synset-15055442-n"/>
    </LexicalEntry>
```

The resulting LMF was validated by the DTD

**Comment by FredsoNerd** [comment]
In edfef023869c61314df07118f544a0b7e190c7f2 we came back to the more readable Word URIs, without quoting. As result, we got URIs such as:

```xml
<https://w3id.org/own-pt/wn30-pt/instances/word-&-n> a wn30:Word ;
<https://w3id.org/own-pt/wn30-pt/instances/word-(militar)+ocupação-n> a wn30:Word ;
<https://w3id.org/own-pt/wn30-pt/instances/word-Solda+de+estanho-n> a wn30:Word ;
<https://w3id.org/own-pt/wn30-pt/instances/word-digno+de+confiança-a> a wn30:Word ;
```
After running the script https://github.com/own-pt/py-ownpt/blob/master/release.sh

**Comment by arademaker** [comment]
Not sure if i understood the last comment. Why using underscore for spaces in the XML but plus in the RDF? I would prefer uniform ids, for XML and RDF... what is the URI in the RDF for `own-pt-word-vapor_d-CloseCurlyQuote-água-n` and `own-pt-word--lpar-de-rpar-_tempo_parcial-a`?

**Comment by FredsoNerd** [comment]
Maybe some misunderstanding. I've already changed the code to generate the ID based on the URI, instead of the Lemma. So, for instance:
```xml
<https://w3id.org/own-pt/wn30-pt/instances/word-vapor+d'água-n> a wn30:Word ;
    wn30:lemma "vapor d'água"@pt ;
    wn30:pos "n" .
```
Gives us the XML ID as follows:
```xml
    <LexicalEntry id="own-pt-word-vapor-plus-d-CloseCurlyQuote-água-n">
      <Lemma partOfSpeech="n" writtenForm="vapor d'água"/>
      <Sense id="own-pt-wordsense-15055442-n-3" synset="own-pt-synset-15055442-n"/>
    </LexicalEntry>
```

**Comment by arademaker** [comment]
I was expecting 

own-pt-word-vapor_d-CloseCurlyQuote-água-n

For both the uri in the RDF and for the xml ID.

**Comment by arademaker** [comment]
Both should be based on lemma not the id based on the uri

**Comment by arademaker** [comment]
@prefix own-en : <https://w3id.org/own/own-pt/instances/> .
@prefix own-pt : <https://w3id.org/own/own-pt/instances/> .
@prefix owns: <https://w3id.org/own/schema/> .


Words:

own-pt:word-Afloramento-n a wn30:Word ;
    wn30:lemma "Afloramento"@pt ;
    wn30:pos "n" .

own-en:word-run-v a wn30:Word ;
    wn30:lemma "run"@en ;
    wn30:otherForm "ran"@en,
        "running"@en ;
    wn30:pos "v" .

For wordsenses:

own-LL:wordsense-00001740-a-1


For synsets:


@prefix own-en : <https://w3id.org/own/own-en/instances/> .
@prefix own-pt : <https://w3id.org/own/own-pt/instances/> .
@prefix owns: <https://w3id.org/own/schema/> .

own-pt:synset-00001740-a a wn30:AdjectiveSynset ;
    skos:inScheme <https://w3id.org/own/own-pt/instances/> ;
    wn30:offset "00001740" ;
    wn30:synsetId "00001740-a" .

own-en:synset-00001740-n a wn30:BaseConcept,
        wn30:NounSynset ;
    skos:inScheme <https://w3id.org/own/own-en/instances/> ;
    wn30:gloss "that which is perceived or known or inferred to have its own distinct existence (living or nonliving)"@en ;
    wn30:lexicographerFile "noun.Tops" ;
    wn30:offset "00001740" ;
    wn30:synsetId "00001740-n" .



https://w3id.org/own/own-pt/instances/word-abafamento-n
own-pt-word-abafamento-n

https://w3id.org/own/own-pt/instances/word-vapor_-CloseCurlyQuote-água-n
own-pt-word-vapor_-CloseCurlyQuote-água-n

https://w3id.org/own/own-en/instances/word-emergent-a
own-en-word-emergent-a

**Comment by FredsoNerd** [comment]
What has to be done :
- [x] **Words local names**: make Word RDF URIs and LMF IDs consistent
- [] **prefix schema**: rename `wn30` to `owns`, for <https://w3id.org/own/schema/>
- [] **prefix pt instances**: use prefix `own-pt` for <https://w3id.org/own/own-pt/instances/>
- [] **prefix en instances**: use prefix `own-en` for <https://w3id.org/own/own-en/instances/>
- [ ] **predicates skos:inScheme in own-pt**: use <https://w3id.org/own/own-pt/instances/>
- [ ] **predicates skos:inScheme in own-en**: use <https://w3id.org/own/own-en/instances/>
- [ ] **review nomlex URIs**: replace <https://w3id.org/own-pt/nomlex/schema/> by <https://w3id.org/own/schema/nomlex/>

**Comment by arademaker** [comment]
For nomlex instances, we can use the respective https://w3id.org/own/own-en/instances/ or https://w3id.org/own/own-pt/instances/. For the schema, ok to use https://w3id.org/own/schema/nomlex/ but this warning flag! We need to rethink https://w3id.org/own/schema/ since that would be a prefix for the previous one.

Two options:

1. make the properties from nomlex part of the general schema 
2. change the more general schema to https://w3id.org/own/schema/wn/

I tend to prefer to merge the nomlex schema into the general schema, that is, we can incorporate the nomlex classes and properties into our general schema for encoding WN in RDF.

**Comment by FredsoNerd** [comment]
In a479a97398ac91dc98e77f6067420b5524c8e47c we update the schemas, after running [schema.sh](https://github.com/own-pt/py-ownpt/blob/b69149919d77043e6e7f05e43a973607d9e2223f/schema.sh). After replacing the URIs, we ran the splitting, to grant the new serialization, including order and prefixes, for instance. Please, take a look.

The resulting files became considerably smaller.

**Comment by FredsoNerd** [comment]
For now, I think we're closing this issue. If there are any new issues related to this discussion, feel free to reopen it.
