### ISSUE TITLE
[verification] Review language tag

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#72]
We should make sure that all words have proper language tags.

**Comment by FredsoNerd** [comment]
Em 4ee848e garantimos que esses tenham tags "pt" ou "en" além de removermos espaçamentos extras durante a ação de formatação. Não apenas Words, como os `rdfs:label`, `wn30:lexicalForm`, `wn30:gloss`, `wn30:example` e `wn30:lemma`, embora haja sugestão para remoção dos lemmas.

Ver #171 e https://github.com/FredsoNerd/py-ownpt/blob/3ab0a5ac80ed988da4a3eeecd21f9b958832f174/pyownpt/repair.py#L210-L226
