### ISSUE TITLE
merge synsets

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#80]
00537153-v ulcerate | ulcerar
(undergo ulceration; "Her stomach ulcerated")

00019982-v ulcerate | ulcerar
(affect with an ulcer; "Her stomach was ulcerated")

**Comment by livyreal** [comment]
demais pares marcados com a hashtag #pairx onde x é um número aleatório apenas para linkar os pares

**Comment by arademaker** [comment]
Conforme sugeri, mudar esta marcação para ```#sameas:NNNNN-t

**Comment by arademaker** [comment]
Vamos anotar nos comentários. Já fiz anotação deste caso que criou o issue.

**Comment by vcvpaiva** [comment]
Alexandre e Livy, esses synsets nao dever ser "merged", um 'e sobre causar e outro sobre sofrer ulcera.
(vejam os hiponimos q sao diferentes!) e' o mesmo caso de americanizar: se tornar or fazer alguem ficar.
em portugues eu concordo que 'e o mesmo verbo, mas os hiponimos sao diferentes, se voces pensarem na arvore estao fazendo dois no's o mesmo, o que vai ligar dois ramos que nao eram ligados antes.
eu ate concordo que pra uma versao melhor de PWN talvez a gente deva fazer esses synsets o mesmo, mas acho que comecar assim na galega, sem ter uma teoria do que vamos fazer 'e um erro crasso. isso nao 'e um erro da PWN e' uma decisao teorica.

**Comment by arademaker** [comment]
bem, este issue já estava fechado porque sua conclusão foi registrar na interface as sugestões de merge usando as hastags ```#sameas:NNNNN-t```.  Ou seja, o issue não era específico sobre estes dois synses, mas sobre como iríamos sugerir merges. Mas de qq forma, para estes dois casos específicos, apaguei da interface os comentários meus de da Livy sugerindo o merge destes synsets.
