### ISSUE TITLE
Morphosemantic links files / blank nodes

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#81]
from @arademaker : temos um problema no morphosemantic-links.nt.gz, primeiro ele tem os links do EXCEL mas também os links projetados em PT, certo? Sugiro separarmos.

Segundo que existem alguns blank nodes, a semântica será que estes caras são outros e nunca serão conectados aos senses blank node do own-pt.nt.gz.  Precisamos primeiro renomear os blank nodes que tivermos em own-pt.nt.gz e wordnet-en.nt.gz.

**Comment by arademaker** [comment]
já temos no own-pt/wordnet-editor função para limpar os wordsense blank.
