### ISSUE TITLE
Floating word senses

### ISSUE THREAD

**Issue by arademaker** [own-pt/openWordnet-PT#86]
select *
{
  ?ws a wn30:WordSense .
  filter not exists {?x ?p ?ws} .
  }

**Comment by vcvpaiva** [comment]
Alexandre por favor adicione o resultado da query, como .txt tambem.

**Comment by arademaker** [comment]
@fcbr the query below do the work:

```
delete { ?ws ?q ?v }
where
{
  ?ws a wn30:WordSense ; ?q ?v .
  filter not exists {?x ?p ?ws . } 
}
```

To make sure, you can run

```
select *
where
{
  ?ws a wn30:WordSense ; ?q ?v .
  filter not exists {?x ?p ?ws . } 
}
order by ?ws 
```

count the number of triples to make sure that after the deletion the number of triples in the store was the expected one.

**Comment by fcbr** [comment]
Feel free to update the triple store.

**Comment by arademaker** [comment]
done 

```
before = 4,526,267
deleted triples = 56
after = 4,526,211
```

closing it. But I didn't update the files in the repo with the new state of the triple store.
