### ISSUE TITLE
Support other synsets types in the "Missing words" reports

### ISSUE THREAD

**Issue by fcbr** [own-pt/openWordnet-PT#97]
Currently http://wnpt.brlcloud.com/wn/prototypes/verbs only checks against the verb synsets, whereas we need similar checks other types of synsets.

**Comment by vcvpaiva** [comment]
we can start by putting back "verbs" on the title of the page, eh? just joking.

**Comment by vcvpaiva** [comment]
Shouldn't we close this issue given that #153 does it?
